# Generated by Django 4.1 on 2022-09-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_deudor', models.CharField(max_length=50)),
                ('conteo_operaciones', models.CharField(max_length=100)),
                ('dias_promedio_pago_ops_pagadas', models.PositiveBigIntegerField()),
                ('umbrales_outliers', models.CharField(max_length=100)),
                ('tipo_pago_max_volumen', models.CharField(max_length=100)),
                ('lista_operaciones', models.CharField(max_length=100)),
            ],
        ),
    ]
